Balmy-protocol/sdk

src/services/quotes/quote-sources/mean-finance.ts, src/services/quotes/source-registry.ts, test/integration/services/quotes/quote-tests-config.ts, test/integration/services/quotes/sources/quote-sources.spec.ts
We are now adding a new quote source for Mean
=> feat: add mean quote source

src/chains.ts, src/services/balances/balance-sources/rpc-balance-source.ts, src/services/gas/gas-service.ts, src/services/multicall/multicall-abi.ts, src/services/multicall/multicall-service.ts, src/services/simulations/simulation-sources/rpc-simulation-source.ts, src/shared/viem.ts, test/integration/services/metadata/metadata-sources.spec.ts
We are now replacing Ethers with Viem internally
=> refactor: use viem internally

package.json, yarn.lock
=> Revert "chore(deps-dev): bump hardhat from 2.13.0 to 2.14.0"

src/services/quotes/quote-sources/0x-quote-source.ts, test/integration/services/quotes/sources/quote-sources.spec.ts
Context: https://twitter.com/0xproject/status/1675987872728637440
=> refactor: make api key mandatory for 0x

src/shared/auto-update-cache.ts, src/shared/index.ts
Added AutoUpdateCache<T> class, for managing and automatically updating a cached value at specified intervals.
=> feat: added AutoUpdateCache

src/services/prices/price-service.ts, src/services/prices/price-sources/aggregator-price-source.ts, src/services/prices/price-sources/cached-price-source.ts, src/services/prices/price-sources/coingecko-price-source.ts, src/services/prices/price-sources/defi-llama-price-source.ts, src/services/prices/price-sources/fastest-price-source.ts, src/services/prices/price-sources/mean-finance-price-source.ts, src/services/prices/price-sources/moralis-price-source.ts, src/services/prices/price-sources/odos-price-source.ts, src/services/prices/price-sources/portals-fi-price-source.ts, src/services/prices/price-sources/prioritized-price-source.ts, src/services/prices/price-sources/utils.ts, src/services/prices/types.ts, src/services/quotes/quote-service.ts, test/integration/services/prices/price-sources.spec.ts, test/unit/services/prices/price-sources/aggregator-price-source.spec.ts, test/unit/services/prices/price-sources/fastest-price-source.spec.ts, test/unit/services/prices/price-sources/prioritized-price-source.spec.ts, test/unit/services/quotes/quote-service.spec.ts
We are now adding a way to fetch multiple historical prices
_Note: we made a sort of hack on the DefiLlama source, since their API is currently not working. If they fix it, then we'll update the code_
=> feat: bulk historical prices

src/services/quotes/quote-sources/0x-quote-source.ts, src/services/quotes/quote-sources/1inch-quote-source.ts, src/services/quotes/quote-sources/changelly-quote-source.ts, src/services/quotes/quote-sources/kyberswap-quote-source.ts, src/services/quotes/quote-sources/odos-quote-source.ts, src/services/quotes/quote-sources/portals-fi-quote-source.ts, src/services/quotes/quote-sources/rango-quote-source.ts, src/services/quotes/quote-sources/wido-quote-source.ts, src/services/quotes/types.ts, test/integration/services/quotes/quote-tests-config.ts
We are now allowing validation support by default, but we are allowing users to disable it via config
=> [BREAKING] feat: add quote validation config

package.json, src/services/quotes/quote-sources/okx-dex-quote-source.ts, src/services/quotes/source-registry.ts, yarn.lock
We are now adding `okx-dex` as a quote source
=> feat: add okx dex quote source

src/services/quotes/quote-sources/xy-finance-quote-source.ts
XY Aggregator doesn't support Blast yet
=> feat: remove blast from xy finance

src/services/quotes/quote-sources/beets-quote-source.ts, src/services/quotes/source-registry.ts
=> feat: add beets quote source

src/services/quotes/quote-sources/bebop-quote-source.ts
Ensures bebop quoter taker and receiver addresses are checksummed
=> fix: bebop quote checksum receiver and taker

src/services/quotes/quote-sources/li-fi-quote-source.ts, src/services/quotes/quote-sources/odos-quote-source.ts, src/services/quotes/quote-sources/open-ocean-quote-source.ts
Before merging, register the REFERRAL_CODE in Odos
=> feat: add support for MODE chain in quote sources

src/services/allowances/allowance-sources/rpc-allowance-source.ts, src/services/balances/balance-sources/rpc-balance-source.ts, src/services/dca/config.ts, src/services/dca/dca-service.ts, src/services/metadata/metadata-sources/rpc-metadata-source.ts, src/services/permit2/permit2-arbitrary-service.ts, src/services/permit2/permit2-quote-service.ts, src/services/permit2/permit2-service.ts, src/services/permit2/types.ts, src/services/permit2/utils/config.ts, src/services/prices/price-sources/odos-price-source.ts, src/services/providers/utils.ts, src/services/quotes/quote-sources/barter-quote-source.ts, src/services/quotes/quote-sources/li-fi-quote-source.ts, src/services/quotes/quote-sources/odos-quote-source.ts, src/services/quotes/quote-sources/oku-quote-source.ts, src/shared/contracts.ts, src/shared/index.ts, src/shared/utils.ts, test/integration/services/permit2/permit2-arbitrary-service.spec.ts
We are now making a small breaking change. We are adding the concept of `Contract`s, that will help us manage the same contract across different chains. Specially if they have different addresses
=> [BREAKING CHANGE] feat: add concept of contracts

src/services/quotes/quote-sources/enso-quote-source.ts
We are now adding the possibility to specify the routing strategy for the quote source `enso`
=> feat: add routing strategy to enso source

src/services/earn/earn-service.ts, src/services/earn/types.ts
We are now adding `getAllowanceTarget`
=> feat: add allowance target

src/services/quotes/quote-sources/paraswap-quote-source.ts
https://developers.paraswap.network/api/get-rate-for-a-token-pair-1#query-parameters
=> feat: add `excludeDEXS` param to paraswap quoter

src/services/earn/earn-service.ts, src/services/earn/index.ts, src/services/earn/types.ts
We are now adding a new property `token` to deposit tokens
=> feat: add type to deposit tokens

src/services/providers/provider-sources/load-balance-provider.ts, src/shared/timeouts.ts
We are now adding a new config that would allow us to add timeout to the load balance provider
=> feat: add timeout to load balancer provider

src/services/quotes/quote-sources/swing-quote-source.ts, src/services/quotes/source-registry.ts
We are now adding a new quote source: swing.xyz
=> feat: add swing quote source

src/chains.ts, src/services/prices/price-sources/coingecko-price-source.ts, src/services/providers/provider-sources/ankr-provider.ts, src/services/providers/provider-sources/drpc-provider.ts, src/services/providers/provider-sources/on-finality-provider.ts, src/services/providers/provider-sources/one-rpc-provider.ts, src/services/quotes/quote-sources/1inch-quote-source.ts, src/shared/defi-llama.ts, test/integration/utils/erc20.ts
We are now renaming the Klaytn chain to Kaia
=> chore: rename klaytn to kaia [breaking change]

src/services/quotes/quote-sources/magpie-quote-source.ts
We are now adding a new config setting to Magpie: `enableRFQ`
=> feat: add new rfq property to magpie
